config = {
    "INK_SEQ_MIN": -500,
    "INK_SEQ_MAX": 500,
    "INK_TIME_SAMPLING_DELTA": 20,
    "INK_PADDING": 4,
    "IMG_SIZE": 224,
    "PRETRAINED_ENCODER_REPO_ID": "google/vit-base-patch16-224-in21k",
    "PRETRAINED_DECODER_REPO_ID": "google-bert/bert-base-cased",
    "FINTUNED_REPO_ID": "ball1433/Handwriting2Latex",
    "max_length": 64,
    "max_new_tokens": 64,
    "INIT_LR": 1e-3,
    "batch_size": 64,
    "num_workers": 4,
    "lora_r": 8,
    "load_lora": False,
    "wandb_project": "Handwriting2Latex",
    "verbose": True,
}
