_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
                - 106
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
